### ISSUE TITLE
superuser login issue

### ISSUE THREAD

**Issue by rishikiranap** [rishikiranap/mocx_2#1]

**Comment by Rishit-Reddy** [comment]
Push latest commit.

**Comment by rishikiranap** [comment]
<img width="1428" alt="Screenshot 2022-11-08 at 10 32 24 PM" src="https://user-images.githubusercontent.com/86961915/200629127-ab1c6636-7713-4a35-874f-3101bd69c71c.png">

Image of the error!!

**Comment by rishikiranap** [comment]
Issue Solved!!
